######################################################################
# Automatically generated by qmake (2.01a) Sat May 5 11:11:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt.cpp
